# Generated by Django 2.1 on 2022-10-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='provinces',
        ),
        migrations.AddField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, choices=[('Gauteng', 'Gauteng'), ('Free State', 'Free State'), ('Limpopo', 'Limpopo')], max_length=100),
        ),
    ]
