# Generated by Django 2.1 on 2022-10-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20221030_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
